apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: testapp
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 5000          # Порт, на котором сервис принимает трафик внутри кластера
      targetPort: 80    # Порт, на который перенаправляется трафик в контейнере
  type: LoadBalancer    # Создает внешний Load Balancer (если поддерживается вашим облачным провайдером)[reference:2]
